test: test.cpp  BP_quantum_func1.cpp BP_basic_func1.cpp
	g++   `pkg-config --cflags itpp` -o test test.cpp BP_quantum_func1.cpp BP_basic_func1.cpp  `pkg-config --libs itpp`
 

gen_Hx:gen_surface.cpp
	g++   -o gen_surface_star gen_surface.cpp
